version: "3.9"

services:
  gandalf_postgres:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=gandalfdb'
      - 'POSTGRES_PASSWORD=gandalfpassword'
      - 'POSTGRES_USER=gandalfuser'
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgresql:/var/lib/postgresql/
    networks:
      - backend

  app:
    build: .
    ports:
      - "8080:8080"
      - "9098:9098"
    depends_on:
      gandalf_postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://liljvrn.ru:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - backend

volumes:
  postgresql: { }

networks:
  backend:
    driver: bridge
